version: '3.3'
services:

  dice:
    container_name: dice
    image: dice
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8080:8080'

  player:
    container_name: player
    image: player
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8081:8081'

  board:
    container_name: board
    image: board
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8082/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8082:8082'
  game:
    container_name: game
    image: game
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8082/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "no"

  db:
    container_name: db
    profiles: ["db"]
    image: mariadb:latest
    restart: "no"
    environment:
      MYSQL_DATABASE: 'app'
      MARIADB_USER: 'app'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - .\sql:/docker-entrypoint-initdb.d/