# docker compose -f .\docker-compose-db.yml --profile sql/mongo up -d
version: '3.3'
services:

  db:
    container_name: db
    image: mariadb:latest
    profiles: ["sql"]
    restart: "no"
    environment:
      MYSQL_DATABASE: 'shutthebox'
      MARIADB_USER: 'test'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    
  mongo:
    container_name: mongo
    image: mongo:4.2
    profiles: ["mongo"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGI_INITDB_DATABASE: shutthebox
    ports:
      - 27017:27017
